--INSERT INTO tipos_documento (tipo_documento) VALUES ('Cédula de ciudadania');
--INSERT INTO tipos_documento (tipo_documento) VALUES ('tarjeta de extranjería');
--INSERT INTO tipos_documento (tipo_documento) VALUES ('cedula de extranjería');
--
--
--INSERT INTO marcas (descripcion_marca) VALUES ('brothers');
--INSERT INTO marcas (descripcion_marca) VALUES ('violets');
--
--INSERT INTO generos (descripcion_genero) VALUES ('masculino');
--INSERT INTO generos (descripcion_genero) VALUES ('femenino');
--
--INSERT INTO colores (descripcion_color) VALUES ('azul claro');
--INSERT INTO colores (descripcion_color) VALUES ('azul oscuro');
--INSERT INTO colores (descripcion_color) VALUES ('negro');
--INSERT INTO colores (descripcion_color) VALUES ('blanco');
--INSERT INTO colores (descripcion_color) VALUES ('rojo');
--INSERT INTO colores (descripcion_color) VALUES ('lila');
--INSERT INTO colores (descripcion_color) VALUES ('gris');
--
--INSERT INTO tallas (descripcion_talla) VALUES ('8');
--INSERT INTO tallas (descripcion_talla) VALUES ('10');
--INSERT INTO tallas (descripcion_talla) VALUES ('12');
--INSERT INTO tallas (descripcion_talla) VALUES ('14');
--INSERT INTO tallas (descripcion_talla) VALUES ('28');
--INSERT INTO tallas (descripcion_talla) VALUES ('30');
--INSERT INTO tallas (descripcion_talla) VALUES ('32');
--INSERT INTO tallas (descripcion_talla) VALUES ('34');
--INSERT INTO tallas (descripcion_talla) VALUES ('S');
--INSERT INTO tallas (descripcion_talla) VALUES ('M');
--INSERT INTO tallas (descripcion_talla) VALUES ('L');
--INSERT INTO tallas (descripcion_talla) VALUES ('XL');
--
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('jeam slim azul claro', 1, 1, 1, 5, 95000, 100, null, 'https://i.ibb.co/Y8MV6dJ/jean-slim-azul-claro.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('jeam slim azul claro', 1, 1, 1, 6, 95000, 100, null, 'https://i.ibb.co/Y8MV6dJ/jean-slim-azul-claro.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('jeam slim azul claro', 1, 1, 1, 7, 95000, 100, null, 'https://i.ibb.co/Y8MV6dJ/jean-slim-azul-claro.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('jeam slim azul claro', 1, 1, 1, 8, 95000, 100, null, 'https://i.ibb.co/Y8MV6dJ/jean-slim-azul-claro.webp');
--
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('jeam slim azul oscuro', 1, 1, 2, 5, 95000, 100, null, 'https://i.ibb.co/7YWrcD7/jean-slim-azul-oscuro.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('jeam slim azul oscuro', 1, 1, 2, 6, 95000, 100, null, 'https://i.ibb.co/7YWrcD7/jean-slim-azul-oscuro.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('jeam slim azul oscuro', 1, 1, 2, 7, 95000, 100, null, 'https://i.ibb.co/7YWrcD7/jean-slim-azul-oscuro.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('jeam slim azul oscuro', 1, 1, 2, 8, 95000, 100, null, 'https://i.ibb.co/7YWrcD7/jean-slim-azul-oscuro.webp');
--
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('jeam slim negro', 1, 1, 3, 5, 95000, 100, null, 'https://i.ibb.co/d0VGP0L/jean-slim-negro.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('jeam slim negro', 1, 1, 3, 6, 95000, 100, null, 'https://i.ibb.co/d0VGP0L/jean-slim-negro.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('jeam slim negro', 1, 1, 3, 7, 95000, 100, null, 'https://i.ibb.co/d0VGP0L/jean-slim-negro.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES('jeam slim negro', 1, 1, 3, 8, 95000, 100, null, 'https://i.ibb.co/d0VGP0L/jean-slim-negro.webp');
--
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('camisa manga larga estampada roja', 1, 1, 5, 9, 70000, 100, null, 'https://i.ibb.co/tX5kGpT/camisa-manga-larga-estampada-roja.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('camisa manga larga estampada roja', 1, 1, 5, 10, 70000, 100, null, 'https://i.ibb.co/tX5kGpT/camisa-manga-larga-estampada-roja.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('camisa manga larga estampada roja', 1, 1, 5, 11, 70000, 100, null, 'https://i.ibb.co/tX5kGpT/camisa-manga-larga-estampada-roja.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('camisa manga larga estampada roja', 1, 1, 5, 12, 70000, 100, null, 'https://i.ibb.co/tX5kGpT/camisa-manga-larga-estampada-roja.webp');
--
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('camisa estampada gris', 1, 1, 7, 9, 70000, 100, null, 'https://i.ibb.co/0r2vfgK/camisa-estampada-gris.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('camisa estampada gris', 1, 1, 7, 10, 70000, 100, null, 'https://i.ibb.co/0r2vfgK/camisa-estampada-gris.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('camisa estampada gris', 1, 1, 7, 11, 70000, 100, null, 'https://i.ibb.co/0r2vfgK/camisa-estampada-gris.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('camisa estampada gris', 1, 1, 7, 12, 70000, 100, null, 'https://i.ibb.co/0r2vfgK/camisa-estampada-gris.webp');
--
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('camisa blanca', 1, 1, 4, 9, 70000, 100, null, 'https://i.ibb.co/C0PypR9/camisa-blanca.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('camisa blanca', 1, 1, 4, 10, 70000, 100, null, 'https://i.ibb.co/C0PypR9/camisa-blanca.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('camisa blanca', 1, 1, 4, 11, 70000, 100, null, 'https://i.ibb.co/C0PypR9/camisa-blanca.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('camisa blanca', 1, 1, 4, 12, 70000, 100, null, 'https://i.ibb.co/C0PypR9/camisa-blanca.webp');
--
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('camiseta manga corta hora de aventura', 1, 1, 4, 9, 70000, 100, null, 'https://i.ibb.co/LN6mBJZ/camiseta-manga-corta-hora-de-aventura.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('camiseta manga corta hora de aventura', 1, 1, 4, 10, 70000, 100, null, 'https://i.ibb.co/LN6mBJZ/camiseta-manga-corta-hora-de-aventura.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('camiseta manga corta hora de aventura', 1, 1, 4, 11, 70000, 100, null, 'https://i.ibb.co/LN6mBJZ/camiseta-manga-corta-hora-de-aventura.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('camiseta manga corta hora de aventura', 1, 1, 4, 12, 70000, 100, null, 'https://i.ibb.co/LN6mBJZ/camiseta-manga-corta-hora-de-aventura.webp');
--
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('jeam delito azul claro', 2, 2, 1, 1, 100000, 100, null, 'https://i.ibb.co/zmCzmMY/jean-delito-azul-claro.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('jeam delito azul claro', 2, 2, 1, 2, 100000, 100, null, 'https://i.ibb.co/zmCzmMY/jean-delito-azul-claro.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('jeam delito azul claro', 2, 2, 1, 3, 100000, 100, null, 'https://i.ibb.co/zmCzmMY/jean-delito-azul-claro.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('jeam delito azul claro', 2, 2, 1, 4, 100000, 100, null, 'https://i.ibb.co/zmCzmMY/jean-delito-azul-claro.webp');
--
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('jeam delito azul oscuro', 2, 2, 2, 1, 100000, 100, null, 'https://i.ibb.co/Zm6Y0Pf/jean-delito-azul-oscuro.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('jeam delito azul oscuro', 2, 2, 2, 2, 100000, 100, null, 'https://i.ibb.co/Zm6Y0Pf/jean-delito-azul-oscuro.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('jeam delito azul oscuro', 2, 2, 2, 3, 100000, 100, null, 'https://i.ibb.co/Zm6Y0Pf/jean-delito-azul-oscuro.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('jeam delito azul oscuro', 2, 2, 2, 4, 100000, 100, null, 'https://i.ibb.co/Zm6Y0Pf/jean-delito-azul-oscuro.webp');
--
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('jeam delito negro', 2, 2, 3, 1, 100000, 100, null, 'https://i.ibb.co/ssnPRn9/jean-delito-negro.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('jeam delito negro', 2, 2, 3, 2, 100000, 100, null, 'https://i.ibb.co/ssnPRn9/jean-delito-negro.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('jeam delito negro', 2, 2, 3, 3, 100000, 100, null, 'https://i.ibb.co/ssnPRn9/jean-delito-negro.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('jeam delito negro', 2, 2, 3, 4, 100000, 100, null, 'https://i.ibb.co/ssnPRn9/jean-delito-negro.webp');
--
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('blusa cuadros azul oscuro', 2, 2, 2, 9, 80000, 100, null, 'https://i.ibb.co/ZKd14B2/blusa-cuadros-azul-oscuro.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('blusa cuadros azul oscuro', 2, 2, 2, 10, 80000, 100, null, 'https://i.ibb.co/ZKd14B2/blusa-cuadros-azul-oscuro.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('blusa cuadros azul oscuro', 2, 2, 2, 11, 80000, 100, null, 'https://i.ibb.co/ZKd14B2/blusa-cuadros-azul-oscuro.webp');
--
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('blusa v con mangas campana blanca', 2, 2, 4, 9, 80000, 100, null, 'https://i.ibb.co/zrTnPgy/blusa-v-con-mangas-campana-blanca.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('blusa v con mangas campana blanca', 2, 2, 4, 10, 80000, 100, null, 'https://i.ibb.co/zrTnPgy/blusa-v-con-mangas-campana-blanca.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('blusa v con mangas campana blanca', 2, 2, 4, 11, 80000, 100, null, 'https://i.ibb.co/zrTnPgy/blusa-v-con-mangas-campana-blanca.webp');
--
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('camiseta uniid_color cuello v', 2, 2, 4, 9, 80000, 100, null, 'https://i.ibb.co/Y8KHk8S/camiseta-uniid_color-cuello-v.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('camiseta uniid_color cuello v', 2, 2, 4, 9, 80000, 100, null, 'https://i.ibb.co/Y8KHk8S/camiseta-uniid_color-cuello-v.webp');
--INSERT INTO productos (descripcion, id_marca, id_genero, id_color, id_talla, valor, stock, busquedas, imagen) VALUES ('camiseta uniid_color cuello v', 2, 2, 4, 9, 80000, 100, null, 'https://i.ibb.co/Y8KHk8S/camiseta-uniid_color-cuello-v.webp');
--
--INSERT INTO usuarios (apellidos, contraseña, correo_usuario, nombres, numero_documento, id_tipo_documento) VALUES('Navarro', '$2a$10$6y315/GIy25gRHSw..v5f.MP4lyc1yf3JsAwoekIcrPPxtFWkAlSy', 'alan@correo.com', 'Alan', '1', 1);
--INSERT INTO usuarios (apellidos, contraseña, correo_usuario, nombres, numero_documento, id_tipo_documento) VALUES('Yepes', '$2a$10$Xm5qYrua5b81YmZTDXSmI.DUDkrRCMknFSPi61osJAa9pfSJM9t0q', 'juan@correo.com', 'Juan', '2', 2);
--INSERT INTO usuarios (apellidos, contraseña, correo_usuario, nombres, numero_documento, id_tipo_documento) VALUES('Naranjo', '$2a$10$OcbudJy1DRltdFMAPXZN3esLPZN/c0OKX.KG.PWz37d6X2i2ejTOy', 'estela@correo.com', 'Estela', '3', 1);
--INSERT INTO usuarios (apellidos, contraseña, correo_usuario, nombres, numero_documento, id_tipo_documento) VALUES('Sepulveda', '$2a$10$xU72vY/BRyg6lnE6RmuIM.XpwDWwXJzOM9C4kEV7KdRIrLKoRr686', 'daniela@correo.com', 'Daniela', '4', 1);
--

